language: ruby

matrix:
  include:
    - rvm: 2.0.0
      env: RACK_VERSION='< 2.0.0'
    - rvm: 2.1.10
      env: RACK_VERSION='< 2.0.0'
    - rvm: 2.2.5
    - rvm: 2.3.1
    - rvm: 2.4.0-preview1

notifications:
  irc: "irc.freenode.org#opal"
