language: ruby

branches:
  only:
  - master
  - /^.*-stable$/
  - /^.*ci-check$/

matrix:
  include:
    - rvm: 2.3
      env: OPAL_VERSION='~> 1.0.0'
    - rvm: 2.4
      env: OPAL_VERSION='~> 1.0.0'
    - rvm: 2.5
      env: OPAL_VERSION='~> 1.0.0'
    - rvm: 2.6
      env: OPAL_VERSION='~> 1.0.0'

notifications:
  irc: "irc.freenode.org#opal"
