language: ruby

branches:
  only:
  - master
  - /^.*-stable$/
  - /^.*ci-check$/

matrix:
  include:
    - rvm: 2.5
      env: OPAL_VERSION='~> 1.0.0'
    - rvm: 2.6
      env: OPAL_VERSION='~> 1.0.0'
    - rvm: 2.7
      env: OPAL_VERSION='~> 1.0.0'
